# Generated by Django 4.2.19 on 2025-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedToFace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.IntegerField(choices=[(1, "男"), (2, "女")])),
                ("image", models.ImageField(upload_to="images/")),
                ("landmarks", models.TextField()),
            ],
        ),
    ]
