# Generated by Django 4.2.19 on 2025-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_seedtoface"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedtoface",
            name="seed",
            field=models.IntegerField(default=0),
        ),
    ]
