# Generated by Django 4.2.19 on 2025-02-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0003_seedtoface_seed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seedtoface",
            name="image",
        ),
    ]
