# Generated by Django 4.2.19 on 2026-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_remove_seedtoface_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnew',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='postnew',
            name='birth_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='出生时辰(小时)'),
        ),
    ]
